[project]
name = "gemma3n-impact-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gradio>=4.44.1",
    "gradio-pdf>=0.0.22",
    "llama-index>=0.12.49",
    "llama-index-embeddings-huggingface>=0.5.5",
    "numpy>=2.0.2",
    "transformers>=4.53.2",
]
